Add files via upload

diff --git a/Modulos/criarusuario b/Modulos/criarusuario
--- a/Modulos/criarusuario
+++ b/Modulos/criarusuario
@@ -127,9 +127,9 @@ fun_edithost() {
     if [[ "$respo" = '1' ]]; then
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althost() {
-        	sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $vivo1\nhttp-proxy $IP 80" $cert01
+            sed -i "7,9"d $cert01
+            sleep 1
+            sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $vivo1\nhttp-proxy $IP 80" $cert01
         }
         fun_bar 'fun_althost'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -139,8 +139,8 @@ fun_edithost() {
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althost2() {
             sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $vivo3\nhttp-proxy $IP 80" $cert01
+            sleep 1
+            sed -i "7i\remote $rmt2 $_Port\nhttp-proxy-option CUSTOM-HEADER Host $vivo3\nhttp-proxy $IP 80" $cert01
         }
         fun_bar 'fun_althost2'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -149,9 +149,9 @@ fun_edithost() {
     elif [[ "$respo" = '3' ]]; then
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althostpay1() {
-        	sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $cert01
+            sed -i "7,9"d $cert01
+            sleep 1
+            sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $cert01
         }
         fun_bar 'fun_althostpay1'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -161,8 +161,8 @@ fun_edithost() {
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althostpay2() {
             sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $rmt2 $_Port\n$payload2\nhttp-proxy $IP 80" $cert01
+            sleep 1
+            sed -i "7i\remote $rmt2 $_Port\n$payload2\nhttp-proxy $IP 80" $cert01
         }
         fun_bar 'fun_althostpay2'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -171,9 +171,9 @@ fun_edithost() {
     elif [[ "$respo" = '5' ]]; then
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althost5() {
-        	sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $rmt3\nhttp-proxy-option CUSTOM-HEADER Host $vivo3\nhttp-proxy $prx:$_Port" $cert01
+            sed -i "7,9"d $cert01
+            sleep 1
+            sed -i "7i\remote $rmt3\nhttp-proxy-option CUSTOM-HEADER Host $vivo3\nhttp-proxy $prx:$_Port" $cert01
         }
         fun_bar 'fun_althost5'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -182,9 +182,9 @@ fun_edithost() {
     elif [[ "$respo" = '6' ]]; then
         echo -e "\n\033[1;32mALTERANDO HOST!\033[0m\n"
         fun_althost6() {
-        	sed -i "7,9"d $cert01
-        	sleep 1
-        	sed -i "7i\remote $IP $_Port\nroute $IP 255.255.255.255 net_gateway\nhttp-proxy 127.0.0.1 8989" $cert01
+            sed -i "7,9"d $cert01
+            sleep 1
+            sed -i "7i\remote $IP $_Port\nroute $IP 255.255.255.255 net_gateway\nhttp-proxy 127.0.0.1 8989" $cert01
         }
         fun_bar 'fun_althost6'
         echo -e "\n\033[1;32mHOST ALTERADO COM SUCESSO!\033[0m"
@@ -211,13 +211,13 @@ fun_edithost() {
             sleep 0.5
             sed -i "7i\remote $IP $_Port\nroute $IP 255.255.255.255 net_gateway\nhttp-proxy 127.0.0.1 8989" $HOME/$username.ovpn
             cp $HOME/$username.ovpn /root/OVPN/$username-bypass.ovpn
-			sed -i "7,9"d $HOME/$username.ovpn
-			sleep 0.5
-			sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $HOME/$username.ovpn
+            sed -i "7,9"d $HOME/$username.ovpn
+            sleep 0.5
+            sed -i "7i\remote $rmt2 $_Port\n$payload1\nhttp-proxy $IP 8080" $HOME/$username.ovpn
             cp $HOME/$username.ovpn /root/OVPN/$username-socks.ovpn
-			sed -i "7,9"d $HOME/$username.ovpn
-			sleep 0.5
-			sed -i "7i\remote $rmt2 $_Port\n$payload2\nhttp-proxy $IP 80" $HOME/$username.ovpn
+            sed -i "7,9"d $HOME/$username.ovpn
+            sleep 0.5
+            sed -i "7i\remote $rmt2 $_Port\n$payload2\nhttp-proxy $IP 80" $HOME/$username.ovpn
             cp $HOME/$username.ovpn /root/OVPN/$username-squid.ovpn
             cd $HOME/OVPN && zip $username.zip *.ovpn >/dev/null 2>&1 && cp $username.zip $HOME/$username.zip
             cd $HOME && rm -rf /root/OVPN >/dev/null 2>&1
@@ -250,149 +250,280 @@ fun_edithost() {
         fun_edithost
     fi
 }
+
+fun_usertoken() {
+    clear
+    tput setaf 7
+    tput setab 4
+    tput bold
+    printf '%30s%s%-15s\n' "Criar Token SSH"
+    tput sgr0
+    echo ""
+    echo -ne "\033[1;32mInsira o Token:\033[1;37m "
+    read username
+    [[ -z $username ]] && {
+        echo -e "\n${cor1}Token vazio ou invalido!${scor}\n"
+        exit 1
+    }
+    [[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
+        echo -e "\n${cor1}Este Token já existe. tente outro Token!${scor}\n"
+        exit 1
+    }
+    [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um Token inválido!${scor}"
+        echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+        exit 1
+    }
+    sizemin=$(echo ${#username})
+    [[ $sizemin -lt 2 ]] && {
+        echo -e "\n${cor1}Você digitou um Token muito curto${scor}"
+        echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mDias para expirar:\033[1;37m "
+    read dias
+    [[ -z $dias ]] && {
+        echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${dias} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
+        exit 1
+    }
+    [[ $dias -lt 1 ]] && {
+        echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mLimite de conexões:\033[1;37m "
+    read sshlimiter
+    [[ -z $sshlimiter ]] && {
+        echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
+        exit 1
+    }
+    [[ $sshlimiter -lt 1 ]] && {
+        echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    password=$(cat /etc/SSHPlus/Token.txt)
+    final=$(date "+%Y-%m-%d" -d "+$dias days")
+    gui=$(date "+%d/%m/%Y" -d "+$dias days")
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+    useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
+    echo "$password" >/etc/SSHPlus/senha/$username
+    echo "$username $sshlimiter" >>/root/usuarios.db
+    clear
+    echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+    echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+    echo -e "\033[1;32mToken: \033[1;37m$username"
+    echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+    echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+
+}
 [[ ! -e /usr/lib/sshplus ]] && exit 0
-tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "Criar Usuário SSH";tput sgr0
+clear
+tput setaf 7
+tput setab 4
+tput bold
+printf '%30s%s%-15s\n' "Criar Usuário SSH"
+tput sgr0
 echo ""
-echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
-[[ -z $username ]] && {
-	echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
-	exit 1
-}
-[[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
-	echo -e "\n${cor1}Este usuário já existe. tente outro nome!${scor}\n"
-	exit 1
-}
-[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
-	echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
-	echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
-	exit 1
-}
-sizemin=$(echo ${#username})
-[[ $sizemin -lt 2 ]] && {
-	echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
-	echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
-	exit 1
-}
-sizemax=$(echo ${#username})
-[[ $sizemax -gt 10 ]] && {
-	echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
-	echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
-	exit 1
-}
-echo -ne "\033[1;32mSenha:\033[1;37m ";read password
-[[ -z $password ]] && {
-	echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
-	exit 1
-}
-sizepass=$(echo ${#password})
-[[ $sizepass -lt 4 ]] && {
-	echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
-	exit 1
-}
-echo -ne "\033[1;32mDias para expirar:\033[1;37m ";read dias
-[[ -z $dias ]] && {
-	echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
-	exit 1
-}
-[[ ${dias} != ?(+|-)+([0-9]) ]] && {
-	echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
-	exit 1
-}
-[[ $dias -lt 1 ]] && {
-	echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
-	exit 1
-}
-echo -ne "\033[1;32mLimite de conexões:\033[1;37m ";read sshlimiter
-[[ -z $sshlimiter ]] && {
-	echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
-	exit 1
-}
-[[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
-	echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
-	exit 1
-}
-[[ $sshlimiter -lt 1 ]] && {
-	echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
-	exit 1
-}
-final=$(date "+%Y-%m-%d" -d "+$dias days")
-gui=$(date "+%d/%m/%Y" -d "+$dias days")
-pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
-useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
-echo "$password" >/etc/SSHPlus/senha/$username
-echo "$username $sshlimiter" >>/root/usuarios.db
-[[ -e /etc/openvpn/server.conf ]] && {
-	echo -ne "\033[1;32mGerar Arquivo Ovpn \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read resp
-	[[ "$resp" = @(s|S) ]] && {
-		rm $username.zip $username.ovpn >/dev/null 2>&1
-		echo -ne "\033[1;32mGerar Com usuário e Senha \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
-		read respost
-		echo -ne "\033[1;32mHost Atual\033[1;37m: \033[1;31m(\033[1;37m$Host\033[1;31m) \033[1;37m- \033[1;32mAlterar \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read oprc
-		[[ "$oprc" = @(s|S) ]] && {
-			fun_edithost
-		} || {
-			fun_geraovpn
-		}
-		gerarovpn() {
-			[[ ! -e "/root/$username.zip" ]] && {
-				zip /root/$username.zip /root/$username.ovpn
-				sleep 1.5
-			}
-		}
-		clear
-		echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
-		echo -e "\n\033[1;32mIP: \033[1;37m$IP"
-		echo -e "\033[1;32mUsuário: \033[1;37m$username"
-		echo -e "\033[1;32mSenha: \033[1;37m$password"
-		echo -e "\033[1;32mExpira em: \033[1;37m$gui"
-		echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
-		sleep 1
-		function aguarde() {
-			helice() {
-				gerarovpn >/dev/null 2>&1 &
-				tput civis
-				while [ -d /proc/$! ]; do
-					for i in / - \\ \|; do
-						sleep .1
-						echo -ne "\e[1D$i"
-					done
-				done
-				tput cnorm
-			}
-			echo ""
-			echo -ne "\033[1;31mCRIANDO OVPN\033[1;33m.\033[1;31m. \033[1;32m"
-			helice
-			echo -e "\e[1DOK"
-		}
-		aguarde
-		VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
-		echo ""
-		[[ -d /var/www/html/openvpn ]] && {
-			mv $HOME/$username.zip /var/www/html/openvpn/$username.zip >/dev/null 2>&1
-			[[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]] && {
-				echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/html/openvpn/$username.zip"
-			} || {
-				echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/openvpn/$username.zip"
-			}
-		} || {
-			echo -e "\033[1;32mDisponivel em\033[1;31m" ~/"$username.zip\033[0m"
-			sleep 1
-		}
-	} || {
-		clear
-		echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
-		echo -e "\n\033[1;32mIP: \033[1;37m$IP"
-		echo -e "\033[1;32mUsuário: \033[1;37m$username"
-		echo -e "\033[1;32mSenha: \033[1;37m$password"
-		echo -e "\033[1;32mExpira em: \033[1;37m$gui"
-		echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
-	}
-} || {
-	clear
-	echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
-	echo -e "\n\033[1;32mIP: \033[1;37m$IP"
-	echo -e "\033[1;32mUsuário: \033[1;37m$username"
-	echo -e "\033[1;32mSenha: \033[1;37m$password"
-	echo -e "\033[1;32mExpira em: \033[1;37m$gui"
-	echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
-}
+read -p "$(echo -ne "\033[1;32mDeseja usar Token? \033[1;33m[s/n]:\033[1;37m") " -e -i n resp
+if [[ "$resp" = 's' ]]; then
+    clear
+    if [ -e "/etc/SSHPlus/Token.txt" ]; then
+        fun_usertoken
+    else
+        clear
+        tput setaf 7
+        tput setab 4
+        tput bold
+        printf '%30s%s%-15s\n' "Senha não encontrada"
+        tput sgr0
+        echo ""
+        echo -ne "\033[1;32mUma senha ainda não foi cadastrada, aperte enter para cadastrar: \033[1;37m "
+        read i
+        clear
+        tput setaf 7
+        tput setab 4
+        tput bold
+        printf '%30s%s%-15s\n' "Criar senha do Token"
+        tput sgr0
+        echo ""
+        echo -ne "\033[1;32mInforme uma senha: \033[1;37m "
+        read senha
+        [[ -z $senha ]] && {
+            echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+            exit 1
+        }
+        echo $senha >/etc/SSHPlus/Token.txt
+        echo -ne "\033[1;32mCadastro feito com sucesso✅\033[1;37m "
+        echo ""
+        sleep 2
+        fun_usertoken
+
+    fi
+
+else
+
+    clear
+    tput setaf 7
+    tput setab 4
+    tput bold
+    printf '%30s%s%-15s\n' "Criar Usuário SSH"
+    tput sgr0
+    echo ""
+    echo -ne "\033[1;32mNome do usuário:\033[1;37m "
+    read username
+    [[ -z $username ]] && {
+        echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+        exit 1
+    }
+    [[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
+        echo -e "\n${cor1}Este usuário já existe. tente outro nome!${scor}\n"
+        exit 1
+    }
+    [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
+        echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+        exit 1
+    }
+    sizemin=$(echo ${#username})
+    [[ $sizemin -lt 2 ]] && {
+        echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+        echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+        exit 1
+    }
+    sizemax=$(echo ${#username})
+    [[ $sizemax -gt 10 ]] && {
+        echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+        echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mSenha:\033[1;37m "
+    read password
+    [[ -z $password ]] && {
+        echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+        exit 1
+    }
+    sizepass=$(echo ${#password})
+    [[ $sizepass -lt 4 ]] && {
+        echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mDias para expirar:\033[1;37m "
+    read dias
+    [[ -z $dias ]] && {
+        echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${dias} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
+        exit 1
+    }
+    [[ $dias -lt 1 ]] && {
+        echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    echo -ne "\033[1;32mLimite de conexões:\033[1;37m "
+    read sshlimiter
+    [[ -z $sshlimiter ]] && {
+        echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
+        exit 1
+    }
+    [[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
+        echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
+        exit 1
+    }
+    [[ $sshlimiter -lt 1 ]] && {
+        echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+        exit 1
+    }
+    final=$(date "+%Y-%m-%d" -d "+$dias days")
+    gui=$(date "+%d/%m/%Y" -d "+$dias days")
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+    useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
+    echo "$password" >/etc/SSHPlus/senha/$username
+    echo "$username $sshlimiter" >>/root/usuarios.db
+    [[ -e /etc/openvpn/server.conf ]] && {
+        echo -ne "\033[1;32mGerar Arquivo Ovpn \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+        read resp
+        [[ "$resp" = @(s|S) ]] && {
+            rm $username.zip $username.ovpn >/dev/null 2>&1
+            echo -ne "\033[1;32mGerar Com usuário e Senha \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+            read respost
+            echo -ne "\033[1;32mHost Atual\033[1;37m: \033[1;31m(\033[1;37m$Host\033[1;31m) \033[1;37m- \033[1;32mAlterar \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+            read oprc
+            [[ "$oprc" = @(s|S) ]] && {
+                fun_edithost
+            } || {
+                fun_geraovpn
+            }
+            gerarovpn() {
+                [[ ! -e "/root/$username.zip" ]] && {
+                    zip /root/$username.zip /root/$username.ovpn
+                    sleep 1.5
+                }
+            }
+            clear
+            echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+            echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+            echo -e "\033[1;32mUsuário: \033[1;37m$username"
+            echo -e "\033[1;32mSenha: \033[1;37m$password"
+            echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+            echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+            sleep 1
+            function aguarde() {
+                helice() {
+                    gerarovpn >/dev/null 2>&1 &
+                    tput civis
+                    while [ -d /proc/$! ]; do
+                        for i in / - \\ \|; do
+                            sleep .1
+                            echo -ne "\e[1D$i"
+                        done
+                    done
+                    tput cnorm
+                }
+                echo ""
+                echo -ne "\033[1;31mCRIANDO OVPN\033[1;33m.\033[1;31m. \033[1;32m"
+                helice
+                echo -e "\e[1DOK"
+            }
+            aguarde
+            VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
+            echo ""
+            [[ -d /var/www/html/openvpn ]] && {
+                mv $HOME/$username.zip /var/www/html/openvpn/$username.zip >/dev/null 2>&1
+                [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]] && {
+                    echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/html/openvpn/$username.zip"
+                } || {
+                    echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/openvpn/$username.zip"
+                }
+            } || {
+                echo -e "\033[1;32mDisponivel em\033[1;31m" ~/"$username.zip\033[0m"
+                sleep 1
+            }
+        } || {
+            clear
+            echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+            echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+            echo -e "\033[1;32mUsuário: \033[1;37m$username"
+            echo -e "\033[1;32mSenha: \033[1;37m$password"
+            echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+            echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+        }
+    } || {
+        clear
+        echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+        echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+        echo -e "\033[1;32mUsuário: \033[1;37m$username"
+        echo -e "\033[1;32mSenha: \033[1;37m$password"
+        echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+        echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+    }
+
+fi
